---
# Headless service for cluster discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.masterService" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: 9300
    protocol: TCP
  selector:
    {{- include "elasticsearch.esSelectorLabels" . | nindent 4 }}
---
# Service for external access
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  {{- with .Values.elasticsearch.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: 9300
    protocol: TCP
  selector:
    {{- include "elasticsearch.esSelectorLabels" . | nindent 4 }}
