{{- if .Values.elasticsearch.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
type: Opaque
data:
  username: {{ "elastic" | b64enc | quote }}
  password: {{ include "elasticsearch.password" . | b64enc | quote }}
{{- end }}
