{{- if and .Values.elasticsearch.security.enabled .Values.elasticsearch.security.tls.enabled .Values.elasticsearch.security.tls.useSelfSignedCerts }}
{{- if not .Values.elasticsearch.security.tls.certificatesSecret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elasticsearch.fullname" . }}-certs-gen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "elasticsearch.fullname" . }}-certs-sa
      containers:
      - name: generate-certs
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        command: ['sh', '-c']
        args:
        - |
          set -e
          CERTS_DIR=/tmp/certs
          mkdir -p ${CERTS_DIR}

          echo "Generating CA..."
          bin/elasticsearch-certutil ca --silent --pem -out /tmp/ca.zip
          unzip /tmp/ca.zip -d ${CERTS_DIR}

          echo "Generating node certificates..."
          bin/elasticsearch-certutil cert --silent --pem \
            --ca-cert ${CERTS_DIR}/ca/ca.crt \
            --ca-key ${CERTS_DIR}/ca/ca.key \
            --in /tmp/instances.yml \
            -out /tmp/certs.zip
          unzip /tmp/certs.zip -d ${CERTS_DIR}

          echo "Creating Kubernetes secret..."
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl

          # Build the secret data
          SECRET_NAME="{{ include "elasticsearch.fullname" . }}-certs"

          # Check if secret exists
          if ./kubectl get secret ${SECRET_NAME} -n {{ .Release.Namespace }} 2>/dev/null; then
            echo "Secret ${SECRET_NAME} already exists, skipping creation"
            exit 0
          fi

          # Create secret from certificate files
          ./kubectl create secret generic ${SECRET_NAME} \
            -n {{ .Release.Namespace }} \
            --from-file=ca.crt=${CERTS_DIR}/ca/ca.crt \
            --from-file=ca.key=${CERTS_DIR}/ca/ca.key \
            {{- range $i := until (int .Values.elasticsearch.replicas) }}
            --from-file={{ include "elasticsearch.fullname" $ }}-{{ $i }}.crt=${CERTS_DIR}/{{ include "elasticsearch.fullname" $ }}-{{ $i }}/{{ include "elasticsearch.fullname" $ }}-{{ $i }}.crt \
            --from-file={{ include "elasticsearch.fullname" $ }}-{{ $i }}.key=${CERTS_DIR}/{{ include "elasticsearch.fullname" $ }}-{{ $i }}/{{ include "elasticsearch.fullname" $ }}-{{ $i }}.key \
            {{- end }}
            --dry-run=client -o yaml | ./kubectl apply -f -

          echo "Certificates generated and stored in secret ${SECRET_NAME}"
        volumeMounts:
        - name: cert-config
          mountPath: /tmp/instances.yml
          subPath: instances.yml
        {{- with .Values.elasticsearch.initContainers.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: cert-config
        configMap:
          name: {{ include "elasticsearch.fullname" . }}-cert-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.fullname" . }}-certs-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elasticsearch.fullname" . }}-certs-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elasticsearch.fullname" . }}-certs-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ include "elasticsearch.fullname" . }}-certs-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "elasticsearch.fullname" . }}-certs-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
