{{- if and .Values.kibana.enabled .Values.kibana.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.kibana.pdb.minAvailable }}
  minAvailable: {{ .Values.kibana.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.kibana.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 6 }}
{{- end }}
