{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  {{- with .Values.kibana.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - name: http
    port: {{ .Values.kibana.service.port }}
    targetPort: 5601
    protocol: TCP
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
{{- end }}
