{{- if .Values.kibana.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-encryption" (include "kibana.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kibana.fullname" . }}-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existingSecret }}
  # Preserve existing keys to avoid breaking encrypted data
  encryptionKey: {{ index $existingSecret.data "encryptionKey" }}
  reportingKey: {{ index $existingSecret.data "reportingKey" }}
  securityKey: {{ index $existingSecret.data "securityKey" }}
  {{- else }}
  # Generate new keys on first install
  # These are base64-encoded 32-character random strings
  encryptionKey: {{ randAlphaNum 32 | b64enc | quote }}
  reportingKey: {{ randAlphaNum 32 | b64enc | quote }}
  securityKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}

