{{- if .Values.networkPolicy.enabled }}
---
# Elasticsearch NetworkPolicy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "elasticsearch.esSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inter-node communication (transport layer)
    - from:
        - podSelector:
            matchLabels:
              {{- include "elasticsearch.esSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9300
    # Allow HTTP access from Kibana
    {{- if .Values.kibana.enabled }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "kibana.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9200
    {{- end }}
    # Allow external access if enabled
    {{- if .Values.networkPolicy.allowExternal }}
    - from: []
      ports:
        - protocol: TCP
          port: 9200
    {{- end }}
    # Allow from specific namespaces
    {{- if .Values.networkPolicy.ingressNSMatchLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNSMatchLabels | nindent 14 }}
          {{- if .Values.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNSPodMatchLabels | nindent 14 }}
          {{- end }}
      ports:
        - protocol: TCP
          port: 9200
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow inter-node communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "elasticsearch.esSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9300
        - protocol: TCP
          port: 9200
---
# Kibana NetworkPolicy
{{- if .Values.kibana.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow external access if enabled
    {{- if .Values.networkPolicy.allowExternal }}
    - from: []
      ports:
        - protocol: TCP
          port: 5601
    {{- end }}
    # Allow from specific namespaces
    {{- if .Values.networkPolicy.ingressNSMatchLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNSMatchLabels | nindent 14 }}
          {{- if .Values.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNSPodMatchLabels | nindent 14 }}
          {{- end }}
      ports:
        - protocol: TCP
          port: 5601
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow connection to Elasticsearch
    - to:
        - podSelector:
            matchLabels:
              {{- include "elasticsearch.esSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9200
{{- end }}
{{- end }}
